models:
- alias: aaa
  context_window_size: 100000
  kwargs:
    max_tokens: 4096
    n: 1
    seed: 0
    temperature: 0
    top_p: 1
  model: gpt-4.1-2025-04-14
- alias: default
  api_base: https://ent.fedgpt.cc/debug/vllm/medium/v1/
  context_window_size: 100000
  kwargs:
    max_tokens: 4096
    n: 1
    seed: 0
    temperature: 0
    top_k: 1
    top_p: 1
  model: openai/fedgpt-medium
provider: litellm_llm
timeout: 120
type: llm
---
models:
- alias: default
  model: Snowflake/snowflake-arctic-embed-l-v2.0
  timeout: 120
provider: huggingface_embedder
type: embedder
---
models:
- alias: default
  model: text-embedding-3-large
  timeout: 120
provider: litellm_embedder
type: embedder
---
endpoint: http://localhost:3000
provider: wren_ui
type: engine
---
connection_info: eyJob3N0IjoicG9zdGdyZXMiLCJwb3J0IjoiNTQzMiIsInVzZXIiOiJwb3N0Z3JlcyIsInBhc3N3b3JkIjoicG9zdGdyZXMiLCJkYXRhYmFzZSI6ImVjb21tZXJjZSJ9
endpoint: http://localhost:8000
manifest: eyJjYXRhbG9nIjoiZWNvbW1lcmNlIiwic2NoZW1hIjoicHVibGljIiwiZGF0YVNvdXJjZSI6InBvc3RncmVzIiwidmlld3MiOltdLCJtZXRyaWNzIjpbXSwibW9kZWxzIjpbeyJuYW1lIjoib2xpc3RfY3VzdG9tZXJzX2RhdGFzZXQiLCJwcmltYXJ5S2V5IjoiY3VzdG9tZXJfaWQiLCJjb2x1bW5zIjpbeyJuYW1lIjoiY3VzdG9tZXJfaWQiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoiY3VzdG9tZXJfdW5pcXVlX2lkIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6ImN1c3RvbWVyX3ppcF9jb2RlX3ByZWZpeCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJjdXN0b21lcl9jaXR5IiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6ImN1c3RvbWVyX3N0YXRlIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319XSwicHJvcGVydGllcyI6e30sInRhYmxlUmVmZXJlbmNlIjp7ImNhdGFsb2ciOiJlY29tbWVyY2UiLCJzY2hlbWEiOiJwdWJsaWMiLCJ0YWJsZSI6Im9saXN0X2N1c3RvbWVyc19kYXRhc2V0In19LHsibmFtZSI6Im9saXN0X2dlb2xvY2F0aW9uX2RhdGFzZXQiLCJjb2x1bW5zIjpbeyJuYW1lIjoiZ2VvbG9jYXRpb25femlwX2NvZGVfcHJlZml4IiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6Imdlb2xvY2F0aW9uX2xhdCIsInR5cGUiOiJudW1iZXIiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6Imdlb2xvY2F0aW9uX2xuZyIsInR5cGUiOiJudW1iZXIiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6Imdlb2xvY2F0aW9uX2NpdHkiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoiZ2VvbG9jYXRpb25fc3RhdGUiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX1dLCJwcm9wZXJ0aWVzIjp7fSwidGFibGVSZWZlcmVuY2UiOnsiY2F0YWxvZyI6ImVjb21tZXJjZSIsInNjaGVtYSI6InB1YmxpYyIsInRhYmxlIjoib2xpc3RfZ2VvbG9jYXRpb25fZGF0YXNldCJ9fSx7Im5hbWUiOiJvbGlzdF9vcmRlcl9pdGVtc19kYXRhc2V0IiwiY29sdW1ucyI6W3sibmFtZSI6Im9yZGVyX2lkIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6Im9yZGVyX2l0ZW1faWQiLCJ0eXBlIjoibnVtYmVyIiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJwcm9kdWN0X2lkIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InNlbGxlcl9pZCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJzaGlwcGluZ19saW1pdF9kYXRlIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InByaWNlIiwidHlwZSI6Im51bWJlciIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoiZnJlaWdodF92YWx1ZSIsInR5cGUiOiJudW1iZXIiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319XSwicHJvcGVydGllcyI6e30sInRhYmxlUmVmZXJlbmNlIjp7ImNhdGFsb2ciOiJlY29tbWVyY2UiLCJzY2hlbWEiOiJwdWJsaWMiLCJ0YWJsZSI6Im9saXN0X29yZGVyX2l0ZW1zX2RhdGFzZXQifX0seyJuYW1lIjoib2xpc3Rfb3JkZXJfcGF5bWVudHNfZGF0YXNldCIsImNvbHVtbnMiOlt7Im5hbWUiOiJvcmRlcl9pZCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJwYXltZW50X3NlcXVlbnRpYWwiLCJ0eXBlIjoibnVtYmVyIiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJwYXltZW50X3R5cGUiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoicGF5bWVudF9pbnN0YWxsbWVudHMiLCJ0eXBlIjoibnVtYmVyIiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJwYXltZW50X3ZhbHVlIiwidHlwZSI6Im51bWJlciIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX1dLCJwcm9wZXJ0aWVzIjp7fSwidGFibGVSZWZlcmVuY2UiOnsiY2F0YWxvZyI6ImVjb21tZXJjZSIsInNjaGVtYSI6InB1YmxpYyIsInRhYmxlIjoib2xpc3Rfb3JkZXJfcGF5bWVudHNfZGF0YXNldCJ9fSx7Im5hbWUiOiJvbGlzdF9vcmRlcl9yZXZpZXdzX2RhdGFzZXQiLCJwcmltYXJ5S2V5IjoicmV2aWV3X2lkIiwiY29sdW1ucyI6W3sibmFtZSI6InJldmlld19pZCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJvcmRlcl9pZCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJyZXZpZXdfc2NvcmUiLCJ0eXBlIjoibnVtYmVyIiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJyZXZpZXdfY29tbWVudF90aXRsZSIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJyZXZpZXdfY29tbWVudF9tZXNzYWdlIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InJldmlld19jcmVhdGlvbl9kYXRlIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InJldmlld19hbnN3ZXJfdGltZXN0YW1wIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319XSwicHJvcGVydGllcyI6e30sInRhYmxlUmVmZXJlbmNlIjp7ImNhdGFsb2ciOiJlY29tbWVyY2UiLCJzY2hlbWEiOiJwdWJsaWMiLCJ0YWJsZSI6Im9saXN0X29yZGVyX3Jldmlld3NfZGF0YXNldCJ9fSx7Im5hbWUiOiJvbGlzdF9vcmRlcnNfZGF0YXNldCIsInByaW1hcnlLZXkiOiJvcmRlcl9pZCIsImNvbHVtbnMiOlt7Im5hbWUiOiJvcmRlcl9pZCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJjdXN0b21lcl9pZCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJvcmRlcl9zdGF0dXMiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoib3JkZXJfcHVyY2hhc2VfdGltZXN0YW1wIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6Im9yZGVyX2FwcHJvdmVkX2F0IiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6Im9yZGVyX2RlbGl2ZXJlZF9jYXJyaWVyX2RhdGUiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoib3JkZXJfZGVsaXZlcmVkX2N1c3RvbWVyX2RhdGUiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoib3JkZXJfZXN0aW1hdGVkX2RlbGl2ZXJ5X2RhdGUiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX1dLCJwcm9wZXJ0aWVzIjp7fSwidGFibGVSZWZlcmVuY2UiOnsiY2F0YWxvZyI6ImVjb21tZXJjZSIsInNjaGVtYSI6InB1YmxpYyIsInRhYmxlIjoib2xpc3Rfb3JkZXJzX2RhdGFzZXQifX0seyJuYW1lIjoib2xpc3RfcHJvZHVjdHNfZGF0YXNldCIsInByaW1hcnlLZXkiOiJwcm9kdWN0X2lkIiwiY29sdW1ucyI6W3sibmFtZSI6InByb2R1Y3RfaWQiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoicHJvZHVjdF9jYXRlZ29yeV9uYW1lIiwidHlwZSI6InRleHQiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InByb2R1Y3RfbmFtZV9sZW5naHQiLCJ0eXBlIjoibnVtYmVyIiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJwcm9kdWN0X2Rlc2NyaXB0aW9uX2xlbmdodCIsInR5cGUiOiJudW1iZXIiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InByb2R1Y3RfcGhvdG9zX3F0eSIsInR5cGUiOiJudW1iZXIiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InByb2R1Y3Rfd2VpZ2h0X2ciLCJ0eXBlIjoibnVtYmVyIiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJwcm9kdWN0X2xlbmd0aF9jbSIsInR5cGUiOiJudW1iZXIiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319LHsibmFtZSI6InByb2R1Y3RfaGVpZ2h0X2NtIiwidHlwZSI6Im51bWJlciIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoicHJvZHVjdF93aWR0aF9jbSIsInR5cGUiOiJudW1iZXIiLCJub3ROdWxsIjpmYWxzZSwicHJvcGVydGllcyI6e319XSwicHJvcGVydGllcyI6e30sInRhYmxlUmVmZXJlbmNlIjp7ImNhdGFsb2ciOiJlY29tbWVyY2UiLCJzY2hlbWEiOiJwdWJsaWMiLCJ0YWJsZSI6Im9saXN0X3Byb2R1Y3RzX2RhdGFzZXQifX0seyJuYW1lIjoib2xpc3Rfc2VsbGVyc19kYXRhc2V0IiwicHJpbWFyeUtleSI6InNlbGxlcl9pZCIsImNvbHVtbnMiOlt7Im5hbWUiOiJzZWxsZXJfaWQiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoic2VsbGVyX3ppcF9jb2RlX3ByZWZpeCIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJzZWxsZXJfY2l0eSIsInR5cGUiOiJ0ZXh0Iiwibm90TnVsbCI6ZmFsc2UsInByb3BlcnRpZXMiOnt9fSx7Im5hbWUiOiJzZWxsZXJfc3RhdGUiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX1dLCJwcm9wZXJ0aWVzIjp7fSwidGFibGVSZWZlcmVuY2UiOnsiY2F0YWxvZyI6ImVjb21tZXJjZSIsInNjaGVtYSI6InB1YmxpYyIsInRhYmxlIjoib2xpc3Rfc2VsbGVyc19kYXRhc2V0In19LHsibmFtZSI6InByb2R1Y3RfY2F0ZWdvcnlfbmFtZV90cmFuc2xhdGlvbiIsImNvbHVtbnMiOlt7Im5hbWUiOiJwcm9kdWN0X2NhdGVnb3J5X25hbWUiLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX0seyJuYW1lIjoicHJvZHVjdF9jYXRlZ29yeV9uYW1lX2VuZ2xpc2giLCJ0eXBlIjoidGV4dCIsIm5vdE51bGwiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7fX1dLCJwcm9wZXJ0aWVzIjp7fSwidGFibGVSZWZlcmVuY2UiOnsiY2F0YWxvZyI6ImVjb21tZXJjZSIsInNjaGVtYSI6InB1YmxpYyIsInRhYmxlIjoicHJvZHVjdF9jYXRlZ29yeV9uYW1lX3RyYW5zbGF0aW9uIn19XSwicmVsYXRpb25zaGlwcyI6W3sibmFtZSI6Im9yZGVyc19jdXN0b21lcnMiLCJtb2RlbHMiOlsib2xpc3Rfb3JkZXJzX2RhdGFzZXQiLCJvbGlzdF9jdXN0b21lcnNfZGF0YXNldCJdLCJqb2luVHlwZSI6Ik1BTllfVE9fT05FIiwiY29uZGl0aW9uIjoiXCJvbGlzdF9vcmRlcnNfZGF0YXNldFwiLlwiY3VzdG9tZXJfaWRcIiA9IFwib2xpc3RfY3VzdG9tZXJzX2RhdGFzZXRcIi5cImN1c3RvbWVyX2lkXCIifSx7Im5hbWUiOiJvcmRlcl9pdGVtc19vcmRlcnMiLCJtb2RlbHMiOlsib2xpc3Rfb3JkZXJfaXRlbXNfZGF0YXNldCIsIm9saXN0X29yZGVyc19kYXRhc2V0Il0sImpvaW5UeXBlIjoiTUFOWV9UT19PTkUiLCJjb25kaXRpb24iOiJcIm9saXN0X29yZGVyX2l0ZW1zX2RhdGFzZXRcIi5cIm9yZGVyX2lkXCIgPSBcIm9saXN0X29yZGVyc19kYXRhc2V0XCIuXCJvcmRlcl9pZFwiIn0seyJuYW1lIjoib3JkZXJfaXRlbXNfcHJvZHVjdHMiLCJtb2RlbHMiOlsib2xpc3Rfb3JkZXJfaXRlbXNfZGF0YXNldCIsIm9saXN0X3Byb2R1Y3RzX2RhdGFzZXQiXSwiam9pblR5cGUiOiJNQU5ZX1RPX09ORSIsImNvbmRpdGlvbiI6Ilwib2xpc3Rfb3JkZXJfaXRlbXNfZGF0YXNldFwiLlwicHJvZHVjdF9pZFwiID0gXCJvbGlzdF9wcm9kdWN0c19kYXRhc2V0XCIuXCJwcm9kdWN0X2lkXCIifSx7Im5hbWUiOiJvcmRlcl9pdGVtc19zZWxsZXJzIiwibW9kZWxzIjpbIm9saXN0X29yZGVyX2l0ZW1zX2RhdGFzZXQiLCJvbGlzdF9zZWxsZXJzX2RhdGFzZXQiXSwiam9pblR5cGUiOiJNQU5ZX1RPX09ORSIsImNvbmRpdGlvbiI6Ilwib2xpc3Rfb3JkZXJfaXRlbXNfZGF0YXNldFwiLlwic2VsbGVyX2lkXCIgPSBcIm9saXN0X3NlbGxlcnNfZGF0YXNldFwiLlwic2VsbGVyX2lkXCIifSx7Im5hbWUiOiJvcmRlcl9wYXltZW50c19vcmRlcnMiLCJtb2RlbHMiOlsib2xpc3Rfb3JkZXJfcGF5bWVudHNfZGF0YXNldCIsIm9saXN0X29yZGVyc19kYXRhc2V0Il0sImpvaW5UeXBlIjoiTUFOWV9UT19PTkUiLCJjb25kaXRpb24iOiJcIm9saXN0X29yZGVyX3BheW1lbnRzX2RhdGFzZXRcIi5cIm9yZGVyX2lkXCIgPSBcIm9saXN0X29yZGVyc19kYXRhc2V0XCIuXCJvcmRlcl9pZFwiIn0seyJuYW1lIjoib3JkZXJfcmV2aWV3c19vcmRlcnMiLCJtb2RlbHMiOlsib2xpc3Rfb3JkZXJfcmV2aWV3c19kYXRhc2V0Iiwib2xpc3Rfb3JkZXJzX2RhdGFzZXQiXSwiam9pblR5cGUiOiJPTkVfVE9fT05FIiwiY29uZGl0aW9uIjoiXCJvbGlzdF9vcmRlcl9yZXZpZXdzX2RhdGFzZXRcIi5cIm9yZGVyX2lkXCIgPSBcIm9saXN0X29yZGVyc19kYXRhc2V0XCIuXCJvcmRlcl9pZFwiIn0seyJuYW1lIjoicHJvZHVjdHNfY2F0ZWdvcnlfdHJhbnNsYXRpb24iLCJtb2RlbHMiOlsib2xpc3RfcHJvZHVjdHNfZGF0YXNldCIsInByb2R1Y3RfY2F0ZWdvcnlfbmFtZV90cmFuc2xhdGlvbiJdLCJqb2luVHlwZSI6Ik1BTllfVE9fT05FIiwiY29uZGl0aW9uIjoiXCJvbGlzdF9wcm9kdWN0c19kYXRhc2V0XCIuXCJwcm9kdWN0X2NhdGVnb3J5X25hbWVcIiA9IFwicHJvZHVjdF9jYXRlZ29yeV9uYW1lX3RyYW5zbGF0aW9uXCIuXCJwcm9kdWN0X2NhdGVnb3J5X25hbWVcIiJ9LHsibmFtZSI6ImN1c3RvbWVyc19nZW9sb2NhdGlvbiIsIm1vZGVscyI6WyJvbGlzdF9jdXN0b21lcnNfZGF0YXNldCIsIm9saXN0X2dlb2xvY2F0aW9uX2RhdGFzZXQiXSwiam9pblR5cGUiOiJNQU5ZX1RPX09ORSIsImNvbmRpdGlvbiI6Ilwib2xpc3RfY3VzdG9tZXJzX2RhdGFzZXRcIi5cImN1c3RvbWVyX3ppcF9jb2RlX3ByZWZpeFwiID0gXCJvbGlzdF9nZW9sb2NhdGlvbl9kYXRhc2V0XCIuXCJnZW9sb2NhdGlvbl96aXBfY29kZV9wcmVmaXhcIiJ9LHsibmFtZSI6InNlbGxlcnNfZ2VvbG9jYXRpb24iLCJtb2RlbHMiOlsib2xpc3Rfc2VsbGVyc19kYXRhc2V0Iiwib2xpc3RfZ2VvbG9jYXRpb25fZGF0YXNldCJdLCJqb2luVHlwZSI6Ik1BTllfVE9fT05FIiwiY29uZGl0aW9uIjoiXCJvbGlzdF9zZWxsZXJzX2RhdGFzZXRcIi5cInNlbGxlcl96aXBfY29kZV9wcmVmaXhcIiA9IFwib2xpc3RfZ2VvbG9jYXRpb25fZGF0YXNldFwiLlwiZ2VvbG9jYXRpb25femlwX2NvZGVfcHJlZml4XCIifV19
provider: wren_ibis
source: postgres
type: engine
---
endpoint: http://localhost:8080
provider: wren_engine
source: postgres
type: engine
---
embedding_model_dim: 1024
location: http://localhost:6333
provider: qdrant
recreate_index: false
timeout: 120
type: document_store
---
pipes:
- document_store: qdrant
  embedder: huggingface_embedder.default
  name: db_schema_indexing
- document_store: qdrant
  embedder: huggingface_embedder.default
  name: historical_question_indexing
- document_store: qdrant
  embedder: huggingface_embedder.default
  name: table_description_indexing
- document_store: qdrant
  embedder: huggingface_embedder.default
  llm: litellm_llm.default
  name: db_schema_retrieval
- document_store: qdrant
  embedder: huggingface_embedder.default
  name: historical_question_retrieval
- document_store: qdrant
  engine: wren_ibis
  llm: litellm_llm.default
  name: sql_generation
- document_store: qdrant
  engine: wren_ibis
  llm: litellm_llm.default
  name: sql_correction
- document_store: qdrant
  engine: wren_ibis
  llm: litellm_llm.default
  name: followup_sql_generation
- llm: litellm_llm.default
  name: sql_answer
- llm: litellm_llm.default
  name: semantics_description
- engine: wren_ibis
  llm: litellm_llm.default
  name: relationship_recommendation
- llm: litellm_llm.default
  name: question_recommendation
- document_store: qdrant
  embedder: huggingface_embedder.default
  llm: litellm_llm.default
  name: question_recommendation_db_schema_retrieval
- document_store: qdrant
  engine: wren_ibis
  llm: litellm_llm.default
  name: question_recommendation_sql_generation
- llm: litellm_llm.default
  name: chart_generation
- llm: litellm_llm.default
  name: chart_adjustment
- document_store: qdrant
  embedder: huggingface_embedder.default
  llm: litellm_llm.default
  name: intent_classification
- llm: litellm_llm.default
  name: misleading_assistance
- llm: litellm_llm.default
  name: data_assistance
- document_store: qdrant
  embedder: huggingface_embedder.default
  name: sql_pairs_indexing
- document_store: qdrant
  embedder: huggingface_embedder.default
  llm: litellm_llm.default
  name: sql_pairs_retrieval
- llm: litellm_llm.default
  name: preprocess_sql_data
- engine: wren_ibis
  name: sql_executor
- llm: litellm_llm.default
  name: user_guide_assistance
- llm: litellm_llm.default
  name: sql_question_generation
- llm: litellm_llm.default
  name: sql_generation_reasoning
- llm: litellm_llm.default
  name: followup_sql_generation_reasoning
- engine: wren_ibis
  llm: litellm_llm.default
  name: sql_regeneration
- llm: litellm_llm.aaa
  name: evaluation
- document_store: qdrant
  embedder: huggingface_embedder.default
  name: instructions_indexing
- document_store: qdrant
  embedder: huggingface_embedder.default
  name: instructions_retrieval
- document_store: qdrant
  engine: wren_ibis
  name: sql_functions_retrieval
- document_store: qdrant
  name: project_meta_indexing
- llm: litellm_llm.default
  name: sql_tables_extraction
type: pipeline
---
settings:
  allow_sql_functions_retrieval: false
  allow_sql_generation_reasoning: true
  allow_sql_samples: false
  column_indexing_batch_size: 50
  datasource: postgres
  development: false
  doc_endpoint: https://docs.getwren.ai
  enable_column_pruning: false
  engine_timeout: 10
  eval_data_db_path: etc/spider1.0/database
  historical_question_retrieval_similarity_threshold: 0.9
  host: 127.0.0.1
  instructions_similarity_threshold: 0.7
  instructions_top_k: 10
  is_oss: true
  langfuse_enable: true
  langfuse_host: https://us.cloud.langfuse.com
  logging_level: INFO
  max_sql_correction_retries: 3
  port: 5556
  query_cache_maxsize: 1000
  query_cache_ttl: 3600
  sql_pairs_retrieval_max_size: 10
  sql_pairs_similarity_threshold: 0.7
  table_column_retrieval_size: 20
  table_retrieval_size: 5
